on:
  push:
    branches:
      - master
    paths:
      - src/userscript.ts
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
          npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update userscript
          file_pattern: userscript.user.js
